# Generated by Django 5.2.13 on 2026-04-25 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_batches', to='datasets.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'run_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('Greedy', 'Greedy'), ('HGA', 'HGA'), ('MILP', 'MILP')], max_length=100)),
                ('population_size', models.IntegerField(blank=True, null=True)),
                ('mutation_rate', models.FloatField(blank=True, null=True)),
                ('crossover_rate', models.FloatField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('generations', models.IntegerField(blank=True, null=True)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('killed', 'Killed'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('progress_pct', models.IntegerField(default=0)),
                ('best_objective', models.FloatField(blank=True, null=True)),
                ('progress_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='datasets.dataset')),
                ('run_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='runs.runbatch')),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['experiment_id'],
                'indexes': [models.Index(fields=['dataset'], name='experiments_dataset_827f12_idx'), models.Index(fields=['run_batch'], name='experiments_run_bat_3c4573_idx'), models.Index(fields=['status'], name='experiments_status_ac7f57_idx')],
            },
        ),
    ]
