# Generated by Django 5.2.13 on 2026-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='no_improve_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
